title: "My Friend Morgan"
description: This is the documentation for the My Friend Morgan ELC project
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: false